In [1]:
import pandas as pd
import numpy as np
import tweepy
import requests as rq
import json
from yelp.client import Client
from tweepy.parsers import JSONParser

from vaderSentiment.vaderSentiment import SentimentIntensityAnalyzer

In [2]:
Consumer_Key = "FSfjjE3eU8euI2t2VUJGh009v"
Consumer_Secret = "B4NEEiXmBOnmJyHS5zo7VxbbMFvjw9DbglolN9c3Nj9ObQYZKU"
Access_Token = "942094172969828352-WCe9ZgRKy30MKWLFYfeWUtzJCCDft7G"
Access_Token_Secret = "XHab1ABIUXKIW2SQrWtH48HImrOHxKqfdwUxRbmUFvylm"

In [3]:
auth = tweepy.OAuthHandler(Consumer_Key, Consumer_Secret)
auth.set_access_token(Access_Token, Access_Token_Secret)

api = tweepy.API(auth, parser=JSONParser())

In [4]:
new_df = pd.read_csv("LA-restaurant.csv")
new_df['LA Sentiment'] = ""
analyzer = SentimentIntensityAnalyzer()

In [5]:
compound_list = []
positive_list = []
negative_list = []
neutral_list = []

# Grab 25 tweets
for index, row in new_df.iterrows():
    public_tweets = api.search(row["User Name"], rpp=100, result_type="recent", geocode="34.0495874,-118.3256491,20mi")

# Loop through all tweets
    for tweet in public_tweets["statuses"]:
        compound = analyzer.polarity_scores(tweet["text"])["compound"]
        pos = analyzer.polarity_scores(tweet["text"])["pos"]
        neu = analyzer.polarity_scores(tweet["text"])["neu"]
        neg = analyzer.polarity_scores(tweet["text"])["neg"]
        
        compound_list.append(compound)
        positive_list.append(pos)
        negative_list.append(neg)
        neutral_list.append(neu)
        
        new_df.set_value(index, 'LA Sentiment', np.mean(compound_list))

In [6]:
new_df['New York Sentiment'] = ""

In [7]:
new_df

,Unnamed: 0,Restaurant Names,User Name,Follower Count,LA Sentiment,New York Sentiment
0,0,Red Lobster,redlobster,296664,0.133653,
1,1,SUBWAYÂ®Restaurants,SUBWAY,2467427,0.0793333,
2,2,Eatalian Cafe,EATALIANCAFE,158,,
3,3,In-N-Out Burger,innoutburger,44775,0.0972244,
4,4,Hustler Casino,HUSTLERCASINOLA,2895,0.09864,
5,5,Roscoe's House of Chicken and Waffles,roscoesofficial,30909,0.120508,
6,6,Little Caesars Pizza,littlecaesars,232112,0.109991,
7,7,The Bicycle Hotel & Casino,BicycleCasino,9333,0.111088,
8,8,Chili's Grill & Bar,Chilis,383907,0.124163,
9,9,Fatburger,Fatburger,14993,0.135205,
10,10,Wingstop,wingstop,208253,0.130132,
11,11,Chuck E. Cheese's,ChuckECheeses,23749,0.143468,
12,12,TGI Fridays,TGIFridays,208950,0.144212,
13,13,Bossa Nova,Bossanovaeats,2321,0.152164,
14,14,Benihana,Benihana,13086,0.153379,
15,15,Olive Garden,olivegarden,385774,0.123984,
16,16,Taco Bell,tacobell,1888502,0.119059,
17,17,Jack Box,JackBox,91621,0.116525,
18,18,Wendy's,Wendys,2288957,0.130658,
19,19,McDonald's,McDonalds,3540391,0.109491,
20,20,Popeyes Chicken,PopeyesChicken,92760,0.100555,
21,21,Panera Bread,askpanera,563,0.0988274,
22,22,Starbucks,Starbucks,11942459,0.0931796,
23,23,Burger King,BurgerKing,1591887,0.0962069,
24,24,Applebee's,Applebees,627246,0.0993979,

In [8]:
compound_list = []
positive_list = []
negative_list = []
neutral_list = []

# Grab 25 tweets
for index, row in new_df.iterrows():
    public_tweets = api.search(row["User Name"], rpp=100, result_type="recent", geocode="40.7485626,-73.9857455,20mi")

# Loop through all tweets
    for tweet in public_tweets["statuses"]:
        compound = analyzer.polarity_scores(tweet["text"])["compound"]
        pos = analyzer.polarity_scores(tweet["text"])["pos"]
        neu = analyzer.polarity_scores(tweet["text"])["neu"]
        neg = analyzer.polarity_scores(tweet["text"])["neg"]
        
        compound_list.append(compound)
        positive_list.append(pos)
        negative_list.append(neg)
        neutral_list.append(neu)
        
        new_df.set_value(index, 'New York Sentiment', np.mean(compound_list))

In [9]:
new_df

,Unnamed: 0,Restaurant Names,User Name,Follower Count,LA Sentiment,New York Sentiment
0,0,Red Lobster,redlobster,296664,0.133653,0.03756
1,1,SUBWAYÂ®Restaurants,SUBWAY,2467427,0.0793333,0.0687233
2,2,Eatalian Cafe,EATALIANCAFE,158,,
3,3,In-N-Out Burger,innoutburger,44775,0.0972244,0.152049
4,4,Hustler Casino,HUSTLERCASINOLA,2895,0.09864,
5,5,Roscoe's House of Chicken and Waffles,roscoesofficial,30909,0.120508,0.157066
6,6,Little Caesars Pizza,littlecaesars,232112,0.109991,0.149893
7,7,The Bicycle Hotel & Casino,BicycleCasino,9333,0.111088,
8,8,Chili's Grill & Bar,Chilis,383907,0.124163,0.145639
9,9,Fatburger,Fatburger,14993,0.135205,0.148543
10,10,Wingstop,wingstop,208253,0.130132,0.13136
11,11,Chuck E. Cheese's,ChuckECheeses,23749,0.143468,0.149817
12,12,TGI Fridays,TGIFridays,208950,0.144212,0.182036
13,13,Bossa Nova,Bossanovaeats,2321,0.152164,
14,14,Benihana,Benihana,13086,0.153379,0.196012
15,15,Olive Garden,olivegarden,385774,0.123984,0.198136
16,16,Taco Bell,tacobell,1888502,0.119059,0.181118
17,17,Jack Box,JackBox,91621,0.116525,0.176523
18,18,Wendy's,Wendys,2288957,0.130658,0.171306
19,19,McDonald's,McDonalds,3540391,0.109491,0.149151
20,20,Popeyes Chicken,PopeyesChicken,92760,0.100555,0.137871
21,21,Panera Bread,askpanera,563,0.0988274,0.133752
22,22,Starbucks,Starbucks,11942459,0.0931796,0.129197
23,23,Burger King,BurgerKing,1591887,0.0962069,0.108833
24,24,Applebee's,Applebees,627246,0.0993979,0.111897

In [10]:
#api = "AIzaSyBqIL-y5BKQwxyrt72Elgvhh9FT7X3Ospg"
#url_geo = "https://maps.googleapis.com/maps/api/geocode/json?address=350+5th+Ave+New+York+NY+10118&key=%s"%(api)
#response2 = rq.get(url_geo).json() 
#print(json.dumps(response2, indent = 4, sort_keys = True))