In [1]:
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import seaborn as sns


with open("city_sentiments.csv") as sentiments:
    avg_sentiment = pd.read_csv(sentiments)
    
avg_sentiment = avg_sentiment[['Chicago', 
                               'New York', 
                               'Houston',
                               'Philadelphia',
                               'Los Angeles',
                               'Atlanta',
                               'Miami']]

avg_sentiment

,Chicago,New York,Houston,Philadelphia,Los Angeles,Atlanta,Miami
0,0.396564,0.394859,0.393194,0.391567,0.389976,0.388421,0.386900
1,0.213683,0.211380,0.209100,0.206844,0.204611,0.202402,0.200214
2,0.218667,0.220409,0.222136,0.223848,0.225545,0.227227,0.228894
3,0.198930,0.198147,0.197370,0.196599,0.195834,0.195075,0.194322
4,0.198746,0.198182,0.197620,0.197062,0.196507,0.195955,0.195406
5,0.210512,0.210741,0.210969,0.211195,0.211421,0.211645,0.211869
6,0.163071,0.162729,0.162390,0.162051,0.161715,0.161379,0.161045
7,0.163424,0.164005,0.164583,0.165160,0.165734,0.166306,0.166875
8,0.151398,0.151126,0.150854,0.150583,0.150313,0.150044,0.149776
9,0.136453,0.136247,0.136040,0.135835,0.135630,0.135426,0.135222
10,0.119471,0.119483,0.119495,0.119508,0.119520,0.119532,0.119544
11,0.164135,0.164916,0.165695,0.166471,0.167246,0.168019,0.168789
12,0.181137,0.181607,0.182075,0.182543,0.183009,0.183474,0.183938
13,0.167351,0.167183,0.167016,0.166848,0.166681,0.166515,0.166348
14,0.133516,0.133395,0.133274,0.133153,0.133032,0.132912,0.132792
15,0.119029,0.118636,0.118245,0.117854,0.117463,0.117074,0.116685
16,0.115975,0.115267,0.114560,0.113854,0.113149,0.112446,0.111743
17,0.110474,0.110521,0.110569,0.110616,0.110663,0.110710,0.110758
18,0.107483,0.107179,0.106875,0.106571,0.106268,0.105965,0.105663
19,0.105764,0.105548,0.105333,0.105118,0.104904,0.104690,0.104476

In [ ]:
x_axis = np.arange(len(target_cities))
sns.set()


target_cities = ["Chicago",
                 "New York",
                 "Houston",
                 "Philadelphia",
                 "Los Angeles",
                 "Atlanta",
                 "Miami"]

x_axis = np.arange(len(target_cities))
sns.set()

color_scheme = ["darkred",
                "darkorange",
                "gold",
                "black",
                "darkblue",
                "darkgreen",
                "darkviolet"]


avg_list = []
for city in target_cities:
    avg_list.append(avg_sentiment[city].mean())
    

    for color_choice in color_scheme:
        sentiment_analysis = plt.bar(x_axis,
                                     avg_list,
                                     color = {color_choice})

        tick_locations = [value for value in x_axis]
        

    
    
    
avg_sentiment_df = pd.DataFrame.from_dict(avg_list)
avg_sentiment_df