In [1]:
import pandas as pd
import numpy as np
import tweepy
import requests as rq
import json
from yelp.client import Client
from tweepy.parsers import JSONParser

from vaderSentiment.vaderSentiment import SentimentIntensityAnalyzer

In [2]:
Consumer_Key = "Ed4RNulN1lp7AbOooHa9STCoU"
Consumer_Secret = "P7cUJlmJZq0VaCY0Jg7COliwQqzK0qYEyUF9Y0idx4ujb3ZlW5"
Access_Token = "839621358724198402-dzdOsx2WWHrSuBwyNUiqSEnTivHozAZ"
Access_Token_Secret = "dCZ80uNRbFDjxdU2EckmNiSckdoATach6Q8zb7YYYE5ER"

In [3]:
auth = tweepy.OAuthHandler(Consumer_Key, Consumer_Secret)
auth.set_access_token(Access_Token, Access_Token_Secret)

api = tweepy.API(auth, parser=JSONParser())

In [4]:
new_df = pd.read_csv("LA-restaurant.csv")
new_df['LA Sentiment'] = ""
analyzer = SentimentIntensityAnalyzer()

In [5]:
compound_list = []
positive_list = []
negative_list = []
neutral_list = []

# Grab 25 tweets
for index, row in new_df.iterrows():
    public_tweets = api.search(row["User Name"], rpp=100, result_type="recent", geocode="34.0495874,-118.3256491,20mi")

# Loop through all tweets
    for tweet in public_tweets["statuses"]:
        compound = analyzer.polarity_scores(tweet["text"])["compound"]
        pos = analyzer.polarity_scores(tweet["text"])["pos"]
        neu = analyzer.polarity_scores(tweet["text"])["neu"]
        neg = analyzer.polarity_scores(tweet["text"])["neg"]
        
        compound_list.append(compound)
        positive_list.append(pos)
        negative_list.append(neg)
        neutral_list.append(neu)
        
        new_df.set_value(index, 'LA Sentiment', np.mean(compound_list))

In [6]:
new_df['New York Sentiment'] = ""

In [7]:
new_df

,Unnamed: 0,Restaurant Names,User Name,Follower Count,LA Sentiment,New York Sentiment
0,0,Red Lobster,redlobster,296664,0.119173,
1,1,SUBWAYÂ®Restaurants,SUBWAY,2467427,0.0937083,
2,2,Eatalian Cafe,EATALIANCAFE,158,,
3,3,In-N-Out Burger,innoutburger,44775,0.0902026,
4,4,Hustler Casino,HUSTLERCASINOLA,2895,0.112589,
5,5,Roscoe's House of Chicken and Waffles,roscoesofficial,30909,0.124109,
6,6,Little Caesars Pizza,littlecaesars,232112,0.131415,
7,7,The Bicycle Hotel & Casino,BicycleCasino,9333,0.124884,
8,8,Chili's Grill & Bar,Chilis,383907,0.103989,
9,9,Fatburger,Fatburger,14993,0.11789,
10,10,Wingstop,wingstop,208253,0.0865958,
11,11,Chuck E. Cheese's,ChuckECheeses,23749,0.100393,
12,12,TGI Fridays,TGIFridays,208950,0.100789,
13,13,Bossa Nova,Bossanovaeats,2321,0.110683,
14,14,Benihana,Benihana,13086,0.0914429,
15,15,Olive Garden,olivegarden,385774,0.0733441,
16,16,Taco Bell,tacobell,1888502,0.0779482,
17,17,Jack Box,JackBox,91621,0.073334,
18,18,Wendy's,Wendys,2288957,0.0694168,
19,19,McDonald's,McDonalds,3540391,0.0632019,
20,20,Popeyes Chicken,PopeyesChicken,92760,0.0671035,
21,21,Panera Bread,askpanera,563,0.065941,
22,22,Starbucks,Starbucks,11942459,0.0647875,
23,23,Burger King,BurgerKing,1591887,0.0698803,
24,24,Applebee's,Applebees,627246,0.0833296,

In [8]:
compound_list = []
positive_list = []
negative_list = []
neutral_list = []

# Grab 25 tweets
for index, row in new_df.iterrows():
    public_tweets = api.search(row["User Name"], rpp=100, result_type="recent", geocode="40.7485626,-73.9857455,20mi")

# Loop through all tweets
    for tweet in public_tweets["statuses"]:
        compound = analyzer.polarity_scores(tweet["text"])["compound"]
        pos = analyzer.polarity_scores(tweet["text"])["pos"]
        neu = analyzer.polarity_scores(tweet["text"])["neu"]
        neg = analyzer.polarity_scores(tweet["text"])["neg"]
        
        compound_list.append(compound)
        positive_list.append(pos)
        negative_list.append(neg)
        neutral_list.append(neu)
        
        new_df.set_value(index, 'New York Sentiment', np.mean(compound_list))

In [9]:
new_df

,Unnamed: 0,Restaurant Names,User Name,Follower Count,LA Sentiment,New York Sentiment
0,0,Red Lobster,redlobster,296664,0.119173,0.16548
1,1,SUBWAYÂ®Restaurants,SUBWAY,2467427,0.0937083,0.0452933
2,2,Eatalian Cafe,EATALIANCAFE,158,,
3,3,In-N-Out Burger,innoutburger,44775,0.0902026,0.158602
4,4,Hustler Casino,HUSTLERCASINOLA,2895,0.112589,
5,5,Roscoe's House of Chicken and Waffles,roscoesofficial,30909,0.124109,0.16334
6,6,Little Caesars Pizza,littlecaesars,232112,0.131415,0.155874
7,7,The Bicycle Hotel & Casino,BicycleCasino,9333,0.124884,
8,8,Chili's Grill & Bar,Chilis,383907,0.103989,0.16812
9,9,Fatburger,Fatburger,14993,0.11789,0.172014
10,10,Wingstop,wingstop,208253,0.0865958,0.0811138
11,11,Chuck E. Cheese's,ChuckECheeses,23749,0.100393,0.104792
12,12,TGI Fridays,TGIFridays,208950,0.100789,0.115258
13,13,Bossa Nova,Bossanovaeats,2321,0.110683,
14,14,Benihana,Benihana,13086,0.0914429,0.109758
15,15,Olive Garden,olivegarden,385774,0.0733441,0.110196
16,16,Taco Bell,tacobell,1888502,0.0779482,0.104617
17,17,Jack Box,JackBox,91621,0.073334,0.110296
18,18,Wendy's,Wendys,2288957,0.0694168,0.11382
19,19,McDonald's,McDonalds,3540391,0.0632019,0.128534
20,20,Popeyes Chicken,PopeyesChicken,92760,0.0671035,0.118466
21,21,Panera Bread,askpanera,563,0.065941,0.116012
22,22,Starbucks,Starbucks,11942459,0.0647875,0.116074
23,23,Burger King,BurgerKing,1591887,0.0698803,0.0956171
24,24,Applebee's,Applebees,627246,0.0833296,0.100132

In [10]:
new_df['Houston Sentiment'] = " "

In [11]:
compound_list = []
positive_list = []
negative_list = []
neutral_list = []

# Grab 25 tweets
for index, row in new_df.iterrows():
    public_tweets = api.search(row["User Name"], rpp=100, result_type="recent", geocode="29.7163165,-95.39087549999999,20mi")

# Loop through all tweets
    for tweet in public_tweets["statuses"]:
        compound = analyzer.polarity_scores(tweet["text"])["compound"]
        pos = analyzer.polarity_scores(tweet["text"])["pos"]
        neu = analyzer.polarity_scores(tweet["text"])["neu"]
        neg = analyzer.polarity_scores(tweet["text"])["neg"]
        
        compound_list.append(compound)
        positive_list.append(pos)
        negative_list.append(neg)
        neutral_list.append(neu)
        
        new_df.set_value(index, 'Houston Sentiment', np.mean(compound_list))

In [12]:
new_df

,Unnamed: 0,Restaurant Names,User Name,Follower Count,LA Sentiment,New York Sentiment,Houston Sentiment
0,0,Red Lobster,redlobster,296664,0.119173,0.16548,0.165527
1,1,SUBWAYÂ®Restaurants,SUBWAY,2467427,0.0937083,0.0452933,0.247507
2,2,Eatalian Cafe,EATALIANCAFE,158,,,
3,3,In-N-Out Burger,innoutburger,44775,0.0902026,0.158602,0.251908
4,4,Hustler Casino,HUSTLERCASINOLA,2895,0.112589,,
5,5,Roscoe's House of Chicken and Waffles,roscoesofficial,30909,0.124109,0.16334,
6,6,Little Caesars Pizza,littlecaesars,232112,0.131415,0.155874,0.209383
7,7,The Bicycle Hotel & Casino,BicycleCasino,9333,0.124884,,
8,8,Chili's Grill & Bar,Chilis,383907,0.103989,0.16812,0.155563
9,9,Fatburger,Fatburger,14993,0.11789,0.172014,0.164109
10,10,Wingstop,wingstop,208253,0.0865958,0.0811138,0.137118
11,11,Chuck E. Cheese's,ChuckECheeses,23749,0.100393,0.104792,0.129125
12,12,TGI Fridays,TGIFridays,208950,0.100789,0.115258,0.138593
13,13,Bossa Nova,Bossanovaeats,2321,0.110683,,
14,14,Benihana,Benihana,13086,0.0914429,0.109758,0.13659
15,15,Olive Garden,olivegarden,385774,0.0733441,0.110196,0.131235
16,16,Taco Bell,tacobell,1888502,0.0779482,0.104617,0.0989676
17,17,Jack Box,JackBox,91621,0.073334,0.110296,0.102023
18,18,Wendy's,Wendys,2288957,0.0694168,0.11382,0.102663
19,19,McDonald's,McDonalds,3540391,0.0632019,0.128534,0.0778901
20,20,Popeyes Chicken,PopeyesChicken,92760,0.0671035,0.118466,0.0920179
21,21,Panera Bread,askpanera,563,0.065941,0.116012,
22,22,Starbucks,Starbucks,11942459,0.0647875,0.116074,0.0975545
23,23,Burger King,BurgerKing,1591887,0.0698803,0.0956171,0.0803584
24,24,Applebee's,Applebees,627246,0.0833296,0.100132,0.095644

In [13]:
new_df['San Francisco Sentiment'] = " "

In [14]:
compound_list = []
positive_list = []
negative_list = []
neutral_list = []

# Grab 25 tweets
for index, row in new_df.iterrows():
    public_tweets = api.search(row["User Name"], rpp=100, result_type="recent", geocode="37.7341834,-122.4892853,20mi")

# Loop through all tweets
    for tweet in public_tweets["statuses"]:
        compound = analyzer.polarity_scores(tweet["text"])["compound"]
        pos = analyzer.polarity_scores(tweet["text"])["pos"]
        neu = analyzer.polarity_scores(tweet["text"])["neu"]
        neg = analyzer.polarity_scores(tweet["text"])["neg"]
        
        compound_list.append(compound)
        positive_list.append(pos)
        negative_list.append(neg)
        neutral_list.append(neu)
        
        new_df.set_value(index, 'San Francisco Sentiment', np.mean(compound_list))

In [15]:
new_df

,Unnamed: 0,Restaurant Names,User Name,Follower Count,LA Sentiment,New York Sentiment,Houston Sentiment,San Francisco Sentiment
0,0,Red Lobster,redlobster,296664,0.119173,0.16548,0.165527,0.0414231
1,1,SUBWAYÂ®Restaurants,SUBWAY,2467427,0.0937083,0.0452933,0.247507,0.127289
2,2,Eatalian Cafe,EATALIANCAFE,158,,,,
3,3,In-N-Out Burger,innoutburger,44775,0.0902026,0.158602,0.251908,0.116444
4,4,Hustler Casino,HUSTLERCASINOLA,2895,0.112589,,,
5,5,Roscoe's House of Chicken and Waffles,roscoesofficial,30909,0.124109,0.16334,,0.113798
6,6,Little Caesars Pizza,littlecaesars,232112,0.131415,0.155874,0.209383,0.10885
7,7,The Bicycle Hotel & Casino,BicycleCasino,9333,0.124884,,,
8,8,Chili's Grill & Bar,Chilis,383907,0.103989,0.16812,0.155563,0.15322
9,9,Fatburger,Fatburger,14993,0.11789,0.172014,0.164109,0.159495
10,10,Wingstop,wingstop,208253,0.0865958,0.0811138,0.137118,0.144232
11,11,Chuck E. Cheese's,ChuckECheeses,23749,0.100393,0.104792,0.129125,0.171304
12,12,TGI Fridays,TGIFridays,208950,0.100789,0.115258,0.138593,0.165742
13,13,Bossa Nova,Bossanovaeats,2321,0.110683,,,
14,14,Benihana,Benihana,13086,0.0914429,0.109758,0.13659,0.149991
15,15,Olive Garden,olivegarden,385774,0.0733441,0.110196,0.131235,0.147252
16,16,Taco Bell,tacobell,1888502,0.0779482,0.104617,0.0989676,0.149826
17,17,Jack Box,JackBox,91621,0.073334,0.110296,0.102023,0.164997
18,18,Wendy's,Wendys,2288957,0.0694168,0.11382,0.102663,0.178945
19,19,McDonald's,McDonalds,3540391,0.0632019,0.128534,0.0778901,0.233473
20,20,Popeyes Chicken,PopeyesChicken,92760,0.0671035,0.118466,0.0920179,0.228916
21,21,Panera Bread,askpanera,563,0.065941,0.116012,,
22,22,Starbucks,Starbucks,11942459,0.0647875,0.116074,0.0975545,0.228897
23,23,Burger King,BurgerKing,1591887,0.0698803,0.0956171,0.0803584,0.21413
24,24,Applebee's,Applebees,627246,0.0833296,0.100132,0.095644,0.207405

In [16]:
new_df['Orlando Sentiment'] = " "

In [17]:
compound_list = []
positive_list = []
negative_list = []
neutral_list = []

# Grab 25 tweets
for index, row in new_df.iterrows():
    public_tweets = api.search(row["User Name"], rpp=100, result_type="recent", geocode="28.385233,-81.563874,20mi")

# Loop through all tweets
    for tweet in public_tweets["statuses"]:
        compound = analyzer.polarity_scores(tweet["text"])["compound"]
        pos = analyzer.polarity_scores(tweet["text"])["pos"]
        neu = analyzer.polarity_scores(tweet["text"])["neu"]
        neg = analyzer.polarity_scores(tweet["text"])["neg"]
        
        compound_list.append(compound)
        positive_list.append(pos)
        negative_list.append(neg)
        neutral_list.append(neu)
        
        new_df.set_value(index, 'Orlando Sentiment', np.mean(compound_list))

In [18]:
new_df

,Unnamed: 0,Restaurant Names,User Name,Follower Count,LA Sentiment,New York Sentiment,Houston Sentiment,San Francisco Sentiment,Orlando Sentiment
0,0,Red Lobster,redlobster,296664,0.119173,0.16548,0.165527,0.0414231,0.28401
1,1,SUBWAYÂ®Restaurants,SUBWAY,2467427,0.0937083,0.0452933,0.247507,0.127289,0.019772
2,2,Eatalian Cafe,EATALIANCAFE,158,,,,,
3,3,In-N-Out Burger,innoutburger,44775,0.0902026,0.158602,0.251908,0.116444,0.0339185
4,4,Hustler Casino,HUSTLERCASINOLA,2895,0.112589,,,,
5,5,Roscoe's House of Chicken and Waffles,roscoesofficial,30909,0.124109,0.16334,,0.113798,
6,6,Little Caesars Pizza,littlecaesars,232112,0.131415,0.155874,0.209383,0.10885,0.113223
7,7,The Bicycle Hotel & Casino,BicycleCasino,9333,0.124884,,,,
8,8,Chili's Grill & Bar,Chilis,383907,0.103989,0.16812,0.155563,0.15322,0.124233
9,9,Fatburger,Fatburger,14993,0.11789,0.172014,0.164109,0.159495,
10,10,Wingstop,wingstop,208253,0.0865958,0.0811138,0.137118,0.144232,0.0800942
11,11,Chuck E. Cheese's,ChuckECheeses,23749,0.100393,0.104792,0.129125,0.171304,0.0826297
12,12,TGI Fridays,TGIFridays,208950,0.100789,0.115258,0.138593,0.165742,0.104426
13,13,Bossa Nova,Bossanovaeats,2321,0.110683,,,,
14,14,Benihana,Benihana,13086,0.0914429,0.109758,0.13659,0.149991,0.0966418
15,15,Olive Garden,olivegarden,385774,0.0733441,0.110196,0.131235,0.147252,0.135784
16,16,Taco Bell,tacobell,1888502,0.0779482,0.104617,0.0989676,0.149826,0.140014
17,17,Jack Box,JackBox,91621,0.073334,0.110296,0.102023,0.164997,0.157129
18,18,Wendy's,Wendys,2288957,0.0694168,0.11382,0.102663,0.178945,0.130389
19,19,McDonald's,McDonalds,3540391,0.0632019,0.128534,0.0778901,0.233473,0.126127
20,20,Popeyes Chicken,PopeyesChicken,92760,0.0671035,0.118466,0.0920179,0.228916,0.119127
21,21,Panera Bread,askpanera,563,0.065941,0.116012,,,0.118131
22,22,Starbucks,Starbucks,11942459,0.0647875,0.116074,0.0975545,0.228897,0.11903
23,23,Burger King,BurgerKing,1591887,0.0698803,0.0956171,0.0803584,0.21413,0.109119
24,24,Applebee's,Applebees,627246,0.0833296,0.100132,0.095644,0.207405,0.115332

In [20]:
new_df.to_csv("twiter_sentiment.csv")

In [19]:
api = "AIzaSyBqIL-y5BKQwxyrt72Elgvhh9FT7X3Ospg"
url_geo = "https://maps.googleapis.com/maps/api/geocode/json?address=Walt+Disney+World+Resort&key=%s"%(api)
response2 = rq.get(url_geo).json() 
print(json.dumps(response2, indent = 4, sort_keys = True))