In [5]:
import pandas as pd
import numpy as np
import tweepy
import requests as rq
import json
from yelp.client import Client
from tweepy.parsers import JSONParser

from vaderSentiment.vaderSentiment import SentimentIntensityAnalyzer

In [6]:
Consumer_Key = "FSfjjE3eU8euI2t2VUJGh009v"
Consumer_Secret = "B4NEEiXmBOnmJyHS5zo7VxbbMFvjw9DbglolN9c3Nj9ObQYZKU"
Access_Token = "942094172969828352-WCe9ZgRKy30MKWLFYfeWUtzJCCDft7G"
Access_Token_Secret = "XHab1ABIUXKIW2SQrWtH48HImrOHxKqfdwUxRbmUFvylm"

In [7]:
auth = tweepy.OAuthHandler(Consumer_Key, Consumer_Secret)
auth.set_access_token(Access_Token, Access_Token_Secret)

api = tweepy.API(auth, parser=JSONParser())

In [8]:
new_df = pd.read_csv("LA-restaurant.csv")
new_df['LA Sentiment'] = ""
analyzer = SentimentIntensityAnalyzer()

In [9]:
compound_list = []
positive_list = []
negative_list = []
neutral_list = []

# Grab 25 tweets
for index, row in new_df.iterrows():
    public_tweets = api.search(row["User Name"], rpp=100, result_type="recent", geocode="34.0495874,-118.3256491,20mi")

# Loop through all tweets
    for tweet in public_tweets["statuses"]:
        compound = analyzer.polarity_scores(tweet["text"])["compound"]
        pos = analyzer.polarity_scores(tweet["text"])["pos"]
        neu = analyzer.polarity_scores(tweet["text"])["neu"]
        neg = analyzer.polarity_scores(tweet["text"])["neg"]
        
        compound_list.append(compound)
        positive_list.append(pos)
        negative_list.append(neg)
        neutral_list.append(neu)
        
        new_df.set_value(index, 'LA Sentiment', np.mean(compound_list))

In [10]:
new_df['New York Sentiment'] = ""

In [11]:
new_df

,Unnamed: 0,Restaurant Names,User Name,Follower Count,LA Sentiment,New York Sentiment
0,0,Red Lobster,redlobster,296664,0.119173,
1,1,SUBWAYÂ®Restaurants,SUBWAY,2467427,0.18015,
2,2,Eatalian Cafe,EATALIANCAFE,158,,
3,3,In-N-Out Burger,innoutburger,44775,0.177593,
4,4,Hustler Casino,HUSTLERCASINOLA,2895,0.175893,
5,5,Roscoe's House of Chicken and Waffles,roscoesofficial,30909,0.173831,
6,6,Little Caesars Pizza,littlecaesars,232112,0.16835,
7,7,The Bicycle Hotel & Casino,BicycleCasino,9333,0.156915,
8,8,Chili's Grill & Bar,Chilis,383907,0.138734,
9,9,Fatburger,Fatburger,14993,0.148157,
10,10,Wingstop,wingstop,208253,0.12476,
11,11,Chuck E. Cheese's,ChuckECheeses,23749,0.134586,
12,12,TGI Fridays,TGIFridays,208950,0.13663,
13,13,Bossa Nova,Bossanovaeats,2321,0.144865,
14,14,Benihana,Benihana,13086,0.128924,
15,15,Olive Garden,olivegarden,385774,0.108735,
16,16,Taco Bell,tacobell,1888502,0.133678,
17,17,Jack Box,JackBox,91621,0.123396,
18,18,Wendy's,Wendys,2288957,0.112532,
19,19,McDonald's,McDonalds,3540391,0.116137,
20,20,Popeyes Chicken,PopeyesChicken,92760,0.120946,
21,21,Panera Bread,askpanera,563,0.118898,
22,22,Starbucks,Starbucks,11942459,0.114006,
23,23,Burger King,BurgerKing,1591887,0.116749,
24,24,Applebee's,Applebees,627246,0.130686,

In [12]:
compound_list = []
positive_list = []
negative_list = []
neutral_list = []

# Grab 25 tweets
for index, row in new_df.iterrows():
    public_tweets = api.search(row["User Name"], rpp=100, result_type="recent", geocode="40.7485626,-73.9857455,20mi")

# Loop through all tweets
    for tweet in public_tweets["statuses"]:
        compound = analyzer.polarity_scores(tweet["text"])["compound"]
        pos = analyzer.polarity_scores(tweet["text"])["pos"]
        neu = analyzer.polarity_scores(tweet["text"])["neu"]
        neg = analyzer.polarity_scores(tweet["text"])["neg"]
        
        compound_list.append(compound)
        positive_list.append(pos)
        negative_list.append(neg)
        neutral_list.append(neu)
        
        new_df.set_value(index, 'New York Sentiment', np.mean(compound_list))

In [13]:
new_df

,Unnamed: 0,Restaurant Names,User Name,Follower Count,LA Sentiment,New York Sentiment
0,0,Red Lobster,redlobster,296664,0.119173,0.17582
1,1,SUBWAYÂ®Restaurants,SUBWAY,2467427,0.18015,0.04183
2,2,Eatalian Cafe,EATALIANCAFE,158,,
3,3,In-N-Out Burger,innoutburger,44775,0.177593,0.156293
4,4,Hustler Casino,HUSTLERCASINOLA,2895,0.175893,
5,5,Roscoe's House of Chicken and Waffles,roscoesofficial,30909,0.173831,0.16113
6,6,Little Caesars Pizza,littlecaesars,232112,0.16835,0.15417
7,7,The Bicycle Hotel & Casino,BicycleCasino,9333,0.156915,
8,8,Chili's Grill & Bar,Chilis,383907,0.138734,0.164182
9,9,Fatburger,Fatburger,14993,0.148157,0.170382
10,10,Wingstop,wingstop,208253,0.12476,0.0738344
11,11,Chuck E. Cheese's,ChuckECheeses,23749,0.134586,0.0985695
12,12,TGI Fridays,TGIFridays,208950,0.13663,0.118537
13,13,Bossa Nova,Bossanovaeats,2321,0.144865,
14,14,Benihana,Benihana,13086,0.128924,0.116945
15,15,Olive Garden,olivegarden,385774,0.108735,0.116667
16,16,Taco Bell,tacobell,1888502,0.133678,0.106529
17,17,Jack Box,JackBox,91621,0.123396,0.112848
18,18,Wendy's,Wendys,2288957,0.112532,0.108612
19,19,McDonald's,McDonalds,3540391,0.116137,0.102216
20,20,Popeyes Chicken,PopeyesChicken,92760,0.120946,0.0900653
21,21,Panera Bread,askpanera,563,0.118898,0.0884578
22,22,Starbucks,Starbucks,11942459,0.114006,0.092326
23,23,Burger King,BurgerKing,1591887,0.116749,0.0780188
24,24,Applebee's,Applebees,627246,0.130686,0.0875257

In [14]:
new_df['Houston Sentiment'] = " "

In [15]:
compound_list = []
positive_list = []
negative_list = []
neutral_list = []

# Grab 25 tweets
for index, row in new_df.iterrows():
    public_tweets = api.search(row["User Name"], rpp=100, result_type="recent", geocode="29.7163165,-95.39087549999999,20mi")

# Loop through all tweets
    for tweet in public_tweets["statuses"]:
        compound = analyzer.polarity_scores(tweet["text"])["compound"]
        pos = analyzer.polarity_scores(tweet["text"])["pos"]
        neu = analyzer.polarity_scores(tweet["text"])["neu"]
        neg = analyzer.polarity_scores(tweet["text"])["neg"]
        
        compound_list.append(compound)
        positive_list.append(pos)
        negative_list.append(neg)
        neutral_list.append(neu)
        
        new_df.set_value(index, 'Houston Sentiment', np.mean(compound_list))

In [16]:
new_df

,Unnamed: 0,Restaurant Names,User Name,Follower Count,LA Sentiment,New York Sentiment,Houston Sentiment
0,0,Red Lobster,redlobster,296664,0.119173,0.17582,0.193793
1,1,SUBWAYÂ®Restaurants,SUBWAY,2467427,0.18015,0.04183,0.07347
2,2,Eatalian Cafe,EATALIANCAFE,158,,,
3,3,In-N-Out Burger,innoutburger,44775,0.177593,0.156293,0.110797
4,4,Hustler Casino,HUSTLERCASINOLA,2895,0.175893,,
5,5,Roscoe's House of Chicken and Waffles,roscoesofficial,30909,0.173831,0.16113,
6,6,Little Caesars Pizza,littlecaesars,232112,0.16835,0.15417,0.109063
7,7,The Bicycle Hotel & Casino,BicycleCasino,9333,0.156915,,
8,8,Chili's Grill & Bar,Chilis,383907,0.138734,0.164182,0.0707179
9,9,Fatburger,Fatburger,14993,0.148157,0.170382,0.0743574
10,10,Wingstop,wingstop,208253,0.12476,0.0738344,0.0398964
11,11,Chuck E. Cheese's,ChuckECheeses,23749,0.134586,0.0985695,0.0329655
12,12,TGI Fridays,TGIFridays,208950,0.13663,0.118537,0.04895
13,13,Bossa Nova,Bossanovaeats,2321,0.144865,,
14,14,Benihana,Benihana,13086,0.128924,0.116945,0.0597333
15,15,Olive Garden,olivegarden,385774,0.108735,0.116667,0.0639408
16,16,Taco Bell,tacobell,1888502,0.133678,0.106529,0.0381889
17,17,Jack Box,JackBox,91621,0.123396,0.112848,0.0473427
18,18,Wendy's,Wendys,2288957,0.112532,0.108612,0.0496006
19,19,McDonald's,McDonalds,3540391,0.116137,0.102216,0.03542
20,20,Popeyes Chicken,PopeyesChicken,92760,0.120946,0.0900653,0.0528872
21,21,Panera Bread,askpanera,563,0.118898,0.0884578,
22,22,Starbucks,Starbucks,11942459,0.114006,0.092326,0.0679857
23,23,Burger King,BurgerKing,1591887,0.116749,0.0780188,0.0521931
24,24,Applebee's,Applebees,627246,0.130686,0.0875257,0.0721399

In [3]:
# api = "AIzaSyBqIL-y5BKQwxyrt72Elgvhh9FT7X3Ospg"
# url_geo = "https://maps.googleapis.com/maps/api/geocode/json?address=6200+Hermann+Park&key=%s"%(api)
# response2 = rq.get(url_geo).json() 
# print(json.dumps(response2, indent = 4, sort_keys = True))

{
    "results": [
        {
            "address_components": [
                {
                    "long_name": "6200",
                    "short_name": "6200",
                    "types": [
                        "street_number"
                    ]
                },
                {
                    "long_name": "Hermann Park Drive",
                    "short_name": "Hermann Park Dr",
                    "types": [
                        "route"
                    ]
                },
                {
                    "long_name": "Southeast Houston",
                    "short_name": "Southeast Houston",
                    "types": [
                        "neighborhood",
                        "political"
                    ]
                },
                {
                    "long_name": "Houston",
                    "short_name": "Houston",
                    "types": [
                        "locality",
                        "political"
                    ]
                },
                {
                    "long_name": "Harris County",
                    "short_name": "Harris County",
                    "types": [
                        "administrative_area_level_2",
                        "political"
                    ]
                },
                {
                    "long_name": "Texas",
                    "short_name": "TX",
                    "types": [
                        "administrative_area_level_1",
                        "political"
                    ]
                },
                {
                    "long_name": "United States",
                    "short_name": "US",
                    "types": [
                        "country",
                        "political"
                    ]
                },
                {
                    "long_name": "77030",
                    "short_name": "77030",
                    "types": [
                        "postal_code"
                    ]
                }
            ],
            "formatted_address": "6200 Hermann Park Dr, Houston, TX 77030, USA",
            "geometry": {
                "location": {
                    "lat": 29.7163165,
                    "lng": -95.39087549999999
                },
                "location_type": "ROOFTOP",
                "viewport": {
                    "northeast": {
                        "lat": 29.7176654802915,
                        "lng": -95.3895265197085
                    },
                    "southwest": {
                        "lat": 29.7149675197085,
                        "lng": -95.3922244802915
                    }
                }
            },
            "partial_match": true,
            "place_id": "ChIJv_bCD4a_QIYRfz9C46gt-Lc",
            "types": [
                "street_address"
            ]
        }
    ],
    "status": "OK"
}